Repository Skyscanner/bpk-svgs, pull requests merged in 2024-04, with the labels that each got.

#70 dependabotBumps
  package-lock.json
  package.json
Labels: dependencies, patch

#72 [BDES-144]: modify ai icon, add new dot icon
  dist/font/BpkIcon.eot
  dist/font/BpkIcon.ttf
  dist/font/BpkIcon.woff
  dist/font/BpkIconIOS.eot
  dist/font/BpkIconIOS.ttf
  dist/font/BpkIconIOS.woff
  dist/font/iconMapping.json
  dist/js/icons/lg/ai.js
  dist/js/icons/lg/dot.js
  dist/js/icons/sm/ai.js
  dist/js/icons/sm/dot.js
  dist/metadata.json
  dist/svgs/icons/lg/ai.svg
  dist/svgs/icons/lg/dot.svg
  dist/svgs/icons/sm/ai.svg
  dist/svgs/icons/sm/dot.svg
  src/icons/lg/ai.svg
  src/icons/lg/dot.svg
  src/icons/sm/ai.svg
  src/icons/sm/dot.svg
  tasks/codepoints.json
Labels: minor

#60 [ARGG-1057]: Setup dependabot to ignore patch versions
  .github/dependabot.yml
Labels: skip-changelog
