Repository Skyscanner/bpk-svgs, pull requests merged in 2025-03, with the labels that each got.

#114 [COR-660] Updates bus icons
  dist/js/icons/lg/bus.jsx
  dist/js/icons/sm/bus.jsx
  dist/svgs/icons/lg/bus.svg
  dist/svgs/icons/sm/bus.svg
  src/icons/lg/bus.svg
  src/icons/sm/bus.svg
Labels: minor, coral

#116 PANGOO-2905/checkbox
  dist/iconMapping.json
  dist/js/icons/sm/check.d.ts
  dist/js/icons/sm/check.jsx
  dist/svgs/icons/sm/check.svg
  src/icons/sm/check.svg
Labels: minor

#118 NO-JIRA: Add new baggage personal item icon to backpack
  dist/iconMapping.json
  dist/js/icons/lg/baggage-personal-item.d.ts
  dist/js/icons/lg/baggage-personal-item.jsx
  dist/js/icons/sm/baggage-personal-item.d.ts
  dist/js/icons/sm/baggage-personal-item.jsx
  dist/metadata.json
  dist/svgs/icons/lg/baggage-personal-item.svg
  dist/svgs/icons/sm/baggage-personal-item.svg
  src/icons/lg/baggage-personal-item.svg
  src/icons/sm/baggage-personal-item.svg
Labels: minor

#119 [PANGOO-2987]Include XL icons to be exported
  dist/js/icons/xl/star-half.d.ts
  dist/js/icons/xl/star-half.jsx
  dist/js/icons/xl/star-outline.d.ts
  dist/js/icons/xl/star-outline.jsx
  dist/js/icons/xl/star.d.ts
  dist/js/icons/xl/star.jsx
  dist/svgs/icons/xl/star-half.svg
  dist/svgs/icons/xl/star-outline.svg
  dist/svgs/icons/xl/star.svg
  gulpfile.mjs
Labels: minor

#120 [NO-JIRA]Update support team
  CONTRIBUTING.md
Labels: skip-changelog
